package com.rhineai.framework

import org.springframework.boot.autoconfigure.EnableAutoConfiguration
import org.springframework.boot.SpringBootConfiguration

@SpringBootConfiguration
@EnableAutoConfiguration
class TestApplication